version: '3.8'

services:
  app:
    build: .
    container_name: stock-dashboard
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FLASK_APP=main.py